export const words = [
  "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog",
  "a", "cat", "runs", "under", "table", "he", "she", "it", "they",
  "we", "you", "I", "quickly", "slowly", "bright", "dark", "happy",
  "sad", "green", "blue", "and", "but", "or", "yet", "so", "for",
  "nor", "on", "in", "at", "by", "with", "about", "against", "between",
  "before", "after", "above", "below", "near", "far", "during", "without",
  "within", "through", "towards", "from", "of", "to", "down", "up", "underneath",
  "beside", "beneath", "across", "along", "among", "around", "behind", "beyond",
  "inside", "outside", "until", "into", "upon", "past", "within", "nearby", "off",
  "alongside", "amid", "amongst", "throughout", "onto", "where", "when", "why",
  "how", "what", "which", "who", "whom", "whose", "while", "whereas", "although",
  "even", "though", "once", "since", "unless", "until", "whether", "whenever",
  "wherever", "anyone", "anything", "everyone", "everything", "someone", "something",
  "nothing", "nobody", "himself", "herself", "itself", "themselves", "ourselves",
  "myself", "yourselves", "such", "few", "many", "some", "any", "all", "more",
  "most", "several", "none", "one", "two", "three", "first", "second", "third",
  "once", "twice", "thrice", "half", "whole", "part", "each", "every", "another",
  "other", "much", "least", "less", "fewer", "little", "moreover", "however",
  "therefore", "thus", "hence", "consequently", "nevertheless", "nonetheless",
  "otherwise", "meanwhile", "furthermore", "besides", "accordingly", "likewise",
  "similarly", "conversely", "instead", "nonetheless", "notwithstanding", "thus",
  "meanwhile", "hence", "otherwise", "although", "because", "since", "unless",
  "if", "though", "whether", "like", "as", "such", "than", "rather", "just",
  "even", "so", "then", "also", "too", "very", "quite", "nearly", "almost",
  "hardly", "scarcely", "barely", "merely", "only", "nearly", "mostly"
];